---

- name: Setting up your very own shitty cluster
  hosts: nodes
  become: true

  tasks:

    - name: Update apt and install libpam-systemd
      ansible.builtin.apt:
        name:
          - libpam-systemd
        state: present
        update_cache: true

    - name: Enable and start dbus.service
      ansible.builtin.systemd:
        name: dbus
        enabled: true
        state: started

    - name: Set node hostname
      ansible.builtin.hostname:
        name: "{{ hostvars[inventory_hostname]['hostname'] }}"
        use: debian

    - name: Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Get version codename
      ansible.builtin.raw: . /etc/os-release && echo "$VERSION_CODENAME"
      register: codename
      changed_when: false

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ codename.stdout }} stable
        state: present
      when: not ansible_check_mode

    - name: Update apt and install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      when: not ansible_check_mode
